config/routes.rb
SuperPc::Application.routes.draw do

  root to: "static_pages#home"

  match 'software' => 'static_pages#software'
  match 'hardware' => 'static_pages#hardware'
  match 'services' => 'static_pages#services'
  match 'about'    => 'static_pages#about'
  match 'contact'  => 'static_pages#contact'

  get "static_pages/home"

  get "static_pages/software"

  get "static_pages/hardware"

  get "static_pages/services"

  get "static_pages/about"

  get "static_pages/contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def software
  end

  def hardware
  end

  def services
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="footer-top">
		
	</div>



	<div class="footer-bottom">
		<span class="copyright">
			© 2013 Super PC Systems
		</span>
	</div>

</footer>

app/views/layouts/_header.html.erb
<header>


	<%= link_to root_path do %>	
		<%= image_tag("logo.png", class: "logo") %>
  <% end %>


	<nav>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Services", services_path %></li>
		<li><%= link_to "Software", software_path %></li>
		<div class='nav-spacer'></div>
		<li><%= link_to "Hardware", hardware_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact Us", contact_path %></li>
	</nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    

    <div class="content">
      <%= yield %>    
    </div>
    
    <%= render 'layouts/footer' %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/hardware.html.erb
<h1>StaticPages#hardware</h1>
<p>Find me in app/views/static_pages/hardware.html.erb</p>

app/views/static_pages/home.html.erb
<div class="hero-container">
	<div class="row">
		<div class="large-6 columns pull-right hero-text">
			<p>Take your business to the next level with our affordable, complete Point Of Sale solutions.</p>
			<div class="top-cta large radius button">Find Out More</div>
		</div>
		<div class="large-6 columns pull-left pos-image">
			<img src="assets/breeze-hero-2.png" alt="" class="breeze">
			<img src="assets/Aldelo-iPad-small.png" alt="" class="ipad">
		</div>
	</div>
</div>





<section class="small-blurbs">
<div class="row">
	<article class="large-4 columns blurb">
		<a href="#big-blurb1" class="scroll">
			<h2>Our Services</h2>
			<p>
				We integrate your new POS system into your restaurant seamlessly and help at every step of the way until completion and beyond.
			</p>
		</a>	
	</article>
	<article class="large-4 columns blurb">
		<a href="#big-blurb2" class="scroll">
			<h2>Our Software</h2>
			<p>
				We'll get you set up and trained with Aldelo POS, an industry standard software with every feature you can imagine, for any ki
				nd of establishment.</p>
		</a>	
	</article>
	<article class="large-4 columns blurb">
		<a href="#big-blurb3" class="scroll">
			<h2>Our Hardware</h2>
			<p>Ca
				sh drawers, printers, customer displays, barcode scanners, even Kitchen Display systems and more. Installation of any equipme
				nt you may want is available to you.
			</p>
		</a>	
	</article>
	</div>
</section>


<section class="large-blurbs">
	<article class="row home-row">
		<div class="large-6 columns">
			<h2>Our Services</h2> 
			<p>We integrate your new POS system into your restaurant seamlessly and help at every step of the way until completion and beyond.</p> 
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla, illo ipsum velit alias iste hic consectetur similique quas molestias assumenda cupiditate libero neque voluptatem et maiores culpa eveniet a illum.</p>
		</div>
		<div class="large-6 columns">
				<!-- <img src="http://placehold.it/690x416" id="big-blurb1">	 -->
				<img src="http://www.valpak.com/img/bpp/MaleTech2.jpg" id="big-blurb1">	
		</div>
	</article>

	<article class="row home-row">
		<div class="large-6 columns">
			<img src="http://placehold.it/690x416"  id="big-blurb2">	
		</div>
		<div class="large-6 columns">
			<h2>Our Software</h2> 
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, voluptates repellat doloribus magni impedit quibusdam nulla minima dolorum nostrum consequatur saepe quod cumque corporis explicabo architecto veritatis laborum assumenda. Ex?</p> 
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, cum, quod, aperiam, magni tenetur odit amet molestiae sapiente nulla animi voluptas quos labore! Fugiat, cupiditate dolor quidem totam quod blanditiis?</p>
		</div>
	</article>

	<article class="row home-row">
		<div class="large-6 columns">
			<h2>Our Hardware</h2> 
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, voluptates repellat doloribus magni impedit quibusdam nulla minima dolorum nostrum consequatur saepe quod cumque corporis explicabo architecto veritatis laborum assumenda. Ex?</p> 
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum, sequi, distinctio est corporis culpa odio minus voluptates ducimus explicabo at quae obcaecati quibusdam hic earum qui aspernatur maxime totam nulla!</p>
		</div>

		<div class="large-6 columns">
			<img src="http://placehold.it/690x416"  id="big-blurb3">	
		</div>
	</article>
</section>

app/views/static_pages/services.html.erb
<h1>StaticPages#services</h1>
<p>Find me in app/views/static_pages/services.html.erb</p>

app/views/static_pages/software.html.erb
<h1>StaticPages#software</h1>
<p>Find me in app/views/static_pages/software.html.erb</p>